### ISSUE TITLE
Username and password 

### ISSUE THREAD

**Issue by fahadgull** [syedzada1100/Cloner-Syed#1]
Sir 
Plz send your username and password 
See this ss
![Screenshot_20210915-155410](https://user-images.githubusercontent.com/90557485/133426173-78eaa350-0e66-4c99-9abd-d0e252f60aa2.png)

**Comment by syedzada1100** [comment]
(PRO-SYED)

**Comment by fahadgull** [comment]
Tnx

**Comment by Farigak07** [comment]
> Sir Plz send your username and password See this ss ![Screenshot_20210915-155410](https://user-images.githubusercontent.com/90557485/133426173-78eaa350-0e66-4c99-9abd-d0e252f60aa2.png)

Plz commnds
